# -*- coding: utf-8 -*-
"""CSE3208 lab1 20/8/24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDW5z900h2r-JjMBlnFQ0FuH0n-K3lDv
"""

file2=open("/content/sample_data/Ai in practice.txt","r")
text=file2.readlines()
print(text)

# function to count no of lines in a file
# find the no of line
import pandas as pd
df="/content/data.tsv"
def count_line(df):
  with open(df,"r",errors='ignore')as file:
    lines=file.readlines()
    return len(lines)

line_count=count_line(df)
print(f'The no of lines in the field is:{line_count}')

file1=open("/content/sample_data/Ai in practice.txt","r")
text= file1.read()
print(text)

df="/content/data.tsv"
def count_fields(df):
  with open(df,"r")as file:
   first_line=file.readline().strip()
   fields=first_line.split()
   return len(fields)

field_count=count_fields(df)
print(f'The no of fields in the first line is:{field_count}')

df=pd.read_csv(df,sep='\t', on_bad_lines='skip', encoding='latin1')
num_instances=df.shape[0]
print(f'The no of instances in the dataset is:{num_instances}')

num_rows = line_count - 1 # subtract 1 for the header
print(f'The no of rows(excluding the header) in the dataset is:{num_rows}')

# No of rows (instances) in the Dataframe
num_instances = df.shape[0]
print(f'The no of instances(rows in dataframe) in the dataset is:{num_instances}')

num_columns = df.shape[1]
print(f'The no of columns in the dataset is:{num_columns}')

