# -*- coding: utf-8 -*-
"""welcome_to_colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11izsQnaZUvR3r1MROAlvsw5IWcN8NUg_
"""

file1=open("/bin/My File.txt")
lines=file1.readlines()
print(lines)

file1=open("/bin/My File.txt")
lines=file1.read()
print(lines)

file_path="/bin/My File.txt"
with open(file_path,'r')as file:
  lines=file.readlines()
length=len(lines)
print(length)